homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone
  temperature_unit: C
  packages: !include_dir_named packages
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: !secret http_baseurl
  api_password: !secret http_apipassword

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

zwave:
  usb_path: /dev/ttyUSB20

# Waiting for Swedish support (https://pypi.python.org/pypi/holidays/)
#binary_sensor:
#  - platform: workday
#    country: SE



# Text to speech
tts:
  - platform: google
    language: 'sv'

logger:
  default: warning
  logs:
    homeassistant.components.automation: info
#    homeassistant.components.device_sun_light_trigger: debug
    #custom_components.restore_states: debug
#    homeassistant.components.apple_tv: debug
    #custom_components.sensor.car_milage_per_month: debug
#    homeassistant.components.xiaomi: debug
#    homeassistant.components.sensor.command_line: debug
#    homeassistant.components.shell_command: debug
#    miflora.miflora_poller: debug
#    homeassistant.components.sensor.miflora: debug
#    homeassistant.core: info

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: mosquitto
  password: mosquitto
  protocol: 3.1 
  discovery: true
  discovery_prefix: home

device_tracker:
#  - platform: icloud
#    username: marcus.ronelius@gmail.com
#    password: !secret icloud_marcus_passwd
#    account_name: Marcus
#    icloud_set_interval: 30

#  - platform: icloud
#    username: schmidt.7@outlook.com
#    password: !secret icloud_katarina_passwd
#    account_name: Katarina
#    icloud_set_interval: 30
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: !secret asuswrt_password

zone:
  name: Work
  latitude: !secret zone_work_latitude
  longitude: !secret zone_work_longitude
  radius: 250
  icon: mdi:worker
  #track_ios: true

switch:

xiaomi:
  gateways:
    - sid:
  #- sid: '34:CE:00:81:2B:DE'
      key: !secret xiaomi

python_script:

light:
  - platform: hue
    host: 192.168.1.8

notify:

recorder:
  purge_days: 7
  db_url: !secret recorder_db_url

#restore_states:

group: !include groups.yaml
scene: !include_dir_list scenes
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
input_boolean: !include input_boolean.yaml
sensor: !include sensors.yaml
shell_command:
  backup_hass: '/home/pi/.homeassistant/scripts/backup_hass.sh'

