homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone
  temperature_unit: C
  customize: !include customize.yaml
  customize_glob:
    "light.*":
      custom_ui_state_card: custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      hide_control: false
      show_last_changed: true
    "*.*":
      custom_ui_state_card: custom-ui
    group.livingroom_environment:
      state_card_mode: badges
    group.kitchen_environment:
      state_card_mode: badges
    group.all_sensors:
      state_card_mode: badges
    group.hallway_sensors:
      state_card_mode: badges
    group.bathroom_sensors:
      state_card_mode: badges
    group.livingroom_sensors:
      state_card_mode: badges
    group.bedroom_sensors:
      state_card_mode: badges
    group.flowers:
      state_card_mode: badges
    group.phone_status:
      state_card_mode: badges

    # Device-aware attributes
    binary_sensor.door_window_sensor_158d00018383cc: # Hallway
      friendly_name: Entrédörr
      group:
        group.hallway_sensors:
          friendly_name: Entrédörr
    binary_sensor.door_window_sensor_158d00018379dd: # Bathroom
      friendly_name: Badrumsdörr
      group:
        group.bathroom_sensors:
          friendly_name: Dörr
    binary_sensor.door_window_sensor_158d00018374aa: # Livingroom
      friendly_name: Fönster Vardagsrum
      group:
        group.livingroom_sensors:
          friendly_name: Fönster
    binary_sensor.door_window_sensor_158d0001837372: # Bedroom
      friendly_name: Fönster Sovrum
      group:
        group.bedroom_sensors:
          friendly_name: Fönster


#    group.livingroom_lights:
#      friendly_name: Yard Light
#      group:
#        group.livingroom_lights:
#          friendly_name: Light


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: !secret http_baseurl
  api_password: !secret http_apipassword
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

zwave:
  usb_path: /dev/ttyUSB20

# Track the sun
#sun:

#binary_sensor:
#  - platform: workday
#    country: SE


camera:
  name: car_location
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.volvo_ete881.attributes.latitude }},{{ states.device_tracker.volvo_ete881.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.volvo_ete881.attributes.latitude }},{{ states.device_tracker.volvo_ete881.attributes.longitude }}
  limit_refetch_to_url_change: true

# Text to speech
tts:
  - platform: google
    language: 'sv'

media_player:
#  - platform: apple_tv
#    host: 192.168.1.3
#    login_id: '00000000-1092-dc12-7d1d-158da0c84566'
#    name: vardagsrum
#  - platform: apple_tv
#    host: 192.168.1.7
#    login_id: '00000000-1092-dc12-7d1d-158da0c84566'
#    name: sovrum
  - platform: spotify
    client_id: !secret spotify_clientid
    client_secret: !secret spotify_secret

apple_tv:
  - name: apple_tv_vardagsrum
    host: 192.168.1.3
    login_id: "00000000-1092-dc12-7d1d-158da0c84566"
    start_off: true
    credentials: "4A2E6F4FD81D6AC3:678148F0334ACC33B969467B388117A85084F1C20F2A3725AB073C6946089F91"
  - name: apple_tv_sovrum
    host: 192.168.1.7
    login_id: "00000000-1092-dc12-7d1d-158da0c84566"
    start_off: true
    credentials: "DC2F5063202BEEDD:4E55203F2655F276DDEF137A5FA029589F1EF4C26BB4C7E3D2D5467D313D7802"

logger:
  default: warning
  logs:
    homeassistant.components.automation: info
#    homeassistant.components.device_sun_light_trigger: debug
    custom_components.restore_states: debug
    homeassistant.components.apple_tv: info
    custom_components.sensor.car_milage_per_month: debug
#    homeassistant.components.xiaomi: debug
#    homeassistant.components.sensor.command_line: debug
#    homeassistant.components.shell_command: debug
#    miflora.miflora_poller: debug
#    homeassistant.components.sensor.miflora: debug
#    homeassistant.core: info

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: mosquitto
  password: mosquitto
  protocol: 3.1 
  discovery: true
  discovery_prefix: home

device_tracker:
#  - platform: icloud
#    username: marcus.ronelius@gmail.com
#    password: N1ntendo1
#    account_name: Marcus
#    icloud_set_interval: 30

#  - platform: icloud
#    username: schmidt.7@outlook.com
#    password: Tegelsten88
#    account_name: Katarina
#    icloud_set_interval: 30
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: !secret asuswrt_password

zone:
  name: Work
  latitude: !secret zone_work_latitude
  longitude: !secret zone_work_longitude
  radius: 250
  icon: mdi:worker
  #track_ios: true

switch:

xiaomi:
  gateways:
    - sid:
  #- sid: '34:CE:00:81:2B:DE'
      key: !secret xiaomi

python_script:

light:
  - platform: hue
    host: 192.168.1.8

ios:

notify:

volvooncall:
  username: marcus.ronelius@gmail.com
  password: !secret volvooncall_password
  name:
    ete881: 'ETE881'

recorder:
  purge_days: 7
  db_url: !secret recorder_db_url

#restore_states:

group: !include groups.yaml
scene: !include_dir_list scenes
automation: !include_dir_merge_list automation
script: !include scripts/radio.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
sensor: !include sensors.yaml
shell_command:
  radio: '/home/pi/.homeassistant/scripts/radio.sh {{ mediaplayer }} {{ station }}'
  backup_hass: '/home/pi/.homeassistant/scripts/backup_hass.sh'

