homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone
  temperature_unit: C
  packages: !include_dir_named packages
  customize: !include customize_custom.yaml

# Enables the frontend
customizer:
  custom_ui: local

# Enables configuration UI
config:

http:
  base_url: !secret http_baseurl
  api_password: !secret http_apipassword

# Checks for available updates
updater:

map:

cloud:

recorder:
  purge_interval: 1
  purge_keep_days: 5

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

zwave:
  usb_path: /dev/ttyUSB20
#  device_config:
#    sensor.aeotec_zw100_multisensor_6_luminance: { polling_intensity: 1 }

# Waiting for Swedish support (https://pypi.python.org/pypi/holidays/)
#binary_sensor:
#  - platform: workday
#    country: SE

homekit:
  auto_start: True
  filter:
    include_domains:
      - cover
      - light
      - binary_sensor
      - climate
      - lock
      - media_player
      - sensor
      - alarm_control_panel
   
#    include_entities: []
    exclude_domains:
      - automation
      - input_boolean
      - script
      - switch
      - device_tracker
    exclude_entities: 
      - light.hue
      - light.tradfri
      - sensor.44615_10033
      - sensor.44615_47214
      - sensor.44615_43081
      - sensor.44615_43084
      - sensor.44615_47212
      - sensor.44615_43161
      - sensor.44615_43009
      - sensor.44615_40071
      - sensor.44615_40008
      - sensor.44615_40033
      - sensor.44615_10012
      - sensor.44615_43416
      - sensor.44615_43437
      - sensor.44615_40017
      - sensor.44615_40012
      - sensor.44615_40020
      - sensor.44615_40018
      - sensor.44615_40019
      - sensor.44615_40022
      - sensor.44615_43420
      - sensor.44615_43424
      - sensor.44615_43123
      - sensor.44615_43122
      - sensor.44615_43136
      - sensor.44615_43124
      - sensor.44615_41026
      - sensor.44615_43125
      - sensor.44615_48745
      - sensor.44615_0
      - sensor.44615_47411
      - sensor.44615_47410
      - sensor.44615_47409
      - sensor.44615_47408
      - sensor.44615_47407
      - sensor.44615_47412
      - sensor.44615_40067
      - sensor.44615_40014
      - sensor.44615_40013
      - sensor.44615_40004
      - sensor.44615_40083
      - sensor.44615_40081
      - sensor.44615_40079
      - sensor.44615_43005
      - sensor.44615_10001
      - sensor.44615_40025
      - sensor.44615_40026
  entity_config:
    alarm_control_panel.solbacken_44_alarm:
      code: !secret alarm_code
    lock.entredorr:
      code: !secret alarm_code

sensor:
  - platform: pi_hole
    host: 127.0.0.1:8081
  - platform: tibber
    access_token: !secret tibber_access_token
  - platform: speedtest
    minute:
      - 0
      - 5
      - 10
      - 15
      - 20
      - 25
      - 30
      - 35
      - 40
      - 45
      - 50
    monitored_conditions:
      - download
      - upload
  - platform: yr
    name: "weather"
    friendly_name: "Väder"
    forecast: 8
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
  - platform: command_line
    name: weather wind direction cmd
    command: 'sh /home/pi/.homeassistant/scripts/wind_direction.sh {{ states.sensor.weather_wind_direction.state }}'
    unit_of_measurement: "Riktning"

  #- platform: command_line
  #  name: rss news feed cmd
  #  command: 'sh /home/pi/.homeassistant/scripts/rss_run.sh https://www.svd.se/?service=rss'

  - platform: google_travel_time
    api_key: !secret google_travel_time_api_key
    origin: zone.home
    destination: zone.work
    name: home to work
    departure_time: 08:00:00

panel_custom:
  - name: alarm
    sidebar_title: Alarm
    sidebar_icon: mdi:security-home
    webcomponent_path: /home/pi/.homeassistant/panels/alarm.html
    config:
      alarmid: alarm_control_panel.solbacken_44_alarm
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml


# Text to speech
tts:
  - platform: google
    language: 'sv'
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key
    aws_secret_access_key: !secret aws_secret_access
    voice: Astrid

device_tracker:
  - platform: owntracks_http
    max_gps_accuracy: 150
#  - platform: icloud
#    username: marcus.ronelius@gmail.com
#    password: !secret icloud_marcus_passwd
#    account_name: Marcus
#    icloud_set_interval: 30

#  - platform: icloud
#    username: schmidt.7@outlook.com
#    password: !secret icloud_katarina_passwd
#    account_name: Katarina
#    icloud_set_interval: 30
#  - platform: asuswrt
#    host: 192.168.1.1
#    username: admin
#    password: !secret asuswrt_password

zone:
  name: Work
  latitude: !secret zone_work_latitude
  longitude: !secret zone_work_longitude
  radius: 250
  icon: mdi:worker
  #track_ios: true

knx:
  config_file: 'xknx.yaml'
  tunneling:
    host: '192.168.1.63'
    port: 3671
    local_ip: '192.168.1.6'

sonos:
  media_player:
    - hosts: 192.168.1.60

media_player:
  - platform: spotify
    client_id: !secret spotify_clientid
    client_secret: !secret spotify_secret

  - platform: webostv
    host: 192.168.1.22
    name: tv_livingroom_upstairs

apple_tv:
  - name: apple_tv_vardagsrum_nedervaning
    host: 192.168.1.3
    login_id: 00000000-1092-dc12-7d1d-158da0c84566
    start_off: true
    credentials: 7C328B2F0BDF6BBE:FDD849B50AD8C23B99435859384776F9D00F6EFDFE0C24884CA552A6BDFCD0B2
  - name: apple_tv_vardagsrum_overvaning
    host: 192.168.1.8
    login_id: 00000000-1092-dc12-7d1d-158da0c84566
    start_off: true
    credentials: EBB9921C76AF30BD:699E00EDA9D28AD67550133E22653DC6E99CB07AC42B421EDD95D9002CC4E646

# xiaomi_aqara:
#   discovery_retry: 10
#   #interface: '192.168.1.100'
#   gateways:
#       key: !secret xiaomi

vacuum:
  - platform: xiaomi_miio
    name: 'Thord'
    host: 192.168.1.193
    token: '544746353737656871414d7168764f35'

python_script:

# hue:
#   bridges:
#     - host: 192.168.1.6

deconz:
  host: 192.168.1.6

notify:
  - platform: webostv
    host: 192.168.1.22
    name: tv_livingroom_upstairs

verisure:
  username: !secret verisure_username
  password: !secret verisure_password
  code_digits: 6

nibe:
    client_id: !secret nibe_client_id
    client_secret: !secret nibe_client_secret
    redirect_uri: http://marschmidt.asuscomm.com:64703/

group: !include groups.yaml

script: !include_dir_merge_named scripts

logger:
  default: warning
  logs:
#    homeassistant.components.automation: info
#    homeassistant.components.zwave: debug
#    homeassistant.components.hue: debug
    homeassistant.components.homekit: debug
#    homeassistant.components.knx: debug
    #homeassistant.components.notify: debug
#    homeassistant.components.script: debug
#    homeassistant.components.recorder: debug
#    homeassistant.components.device_tracker.owntracks_http: debug
#    homeassistant.components.media_player.spotify: info
    #custom_components.restore_states: debug
#    homeassistant.components.apple_tv: debug
#    custom_components.news: debug
#    homeassistant.components.xiaomi: debug
#    homeassistant.components.sensor.command_line: debug
#    homeassistant.components.shell_command: debug
#    miflora.miflora_poller: debug
#    homeassistant.components.sensor.miflora: debug
#    homeassistant.core: info
