homeassistant:
  name: !secret home_name
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: !secret home_timezone
  temperature_unit: C
  customize: !include customize.yaml


# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  base_url: !secret http_baseurl
  api_password: !secret http_apipassword
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

zwave:
  usb_path: /dev/ttyUSB20

# Track the sun
#sun:

#binary_sensor:
#  - platform: workday
#    country: SE



# Sensors
sensor:
  - platform: miflora
    name: miflower_kitchenflower
    mac: 'C4:7C:8D:61:FD:A7'
    monitored_conditions:
      - moisture
      - temperature
      - light
      - conductivity
      - battery

  - platform: yr
    name: "weather"
    friendly_name: "Väder"
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
  - platform: speedtest
    minute:
      - 0
      - 5
      - 10
      - 15
      - 20
      - 25
      - 30
      - 35
      - 40
      - 45
      - 50
    monitored_conditions:
      - download
      - upload

  - platform: template
    sensors:
      ete881_odometer_template:
        unit_of_measurement: 'mil'
        value_template: '{{ states.sensor.ete881_odometer.state | multiply(1) / 10 }}'
      ete881_range_template:
        unit_of_measurement: 'mil'
        value_template: '{{ states.sensor.ete881_range.state | multiply(1) / 10 }}'
      yr_wind_direction_template:
        value_template: '{{ states.sensor.yr_wind_direction.state | int }}'

  - platform: command_line
    name: yr wind direction cmd
    command: 'sh /home/pi/.homeassistant/scripts/wind_direction.sh {{ states.sensor.yr_wind_direction_template.state }}'
    unit_of_measurement: "Vind"

  - platform: mqtt
    name: "car_regnr"
    state_topic: "/home/car"
    value_template: '{{ value_json.regnr }}'

  - platform: mqtt
    name: "car_model"
    state_topic: "/home/car"
    value_template: '{{ value_json.model }}'

  - platform: mqtt
    name: "car_locked_state"
    state_topic: "/home/car"
    value_template: '{{ value_json.locked }}'

  - platform: mqtt
    name: car_location_latitude
    state_topic: "/home/car"
    value_template: '{{ value_json.location_latitude}}'

  - platform: mqtt
    name: car_location_longitude
    state_topic: "/home/car"
    value_template: '{{ value_json.location_longitude}}'

  - platform: template
    sensors:
      car_locked:
        value_template: '{% if is_state("sensor.car_locked_state", False) %} Öppet {% else %} Låst {% endif %}'
        friendly_name: Dörrar & lås

camera:
  name: car_location
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.volvo_ete881.attributes.latitude }},{{ states.device_tracker.volvo_ete881.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.volvo_ete881.attributes.latitude }},{{ states.device_tracker.volvo_ete881.attributes.longitude }}
  limit_refetch_to_url_change: true

# Text to speech
tts:
  - platform: google
    language: 'sv'

media_player:
#  - platform: apple_tv
#    host: 192.168.1.3
#    login_id: '00000000-1092-dc12-7d1d-158da0c84566'
#    name: vardagsrum
#  - platform: apple_tv
#    host: 192.168.1.7
#    login_id: '00000000-1092-dc12-7d1d-158da0c84566'
#    name: sovrum
  - platform: spotify
    client_id: !secret spotify_clientid
    client_secret: !secret spotify_secret

apple_tv:
  - name: apple_tv_vardagsrum
    host: 192.168.1.3
    login_id: "00000000-1092-dc12-7d1d-158da0c84566"
    start_off: false
    credentials: "4A2E6F4FD81D6AC3:678148F0334ACC33B969467B388117A85084F1C20F2A3725AB073C6946089F91"

  - name: apple_tv_sovrum
    host: 192.168.1.7
    login_id: "00000000-1092-dc12-7d1d-158da0c84566"
    start_off: false

logger:
  default: warning
  logs:
    homeassistant.components.automation: info
#    homeassistant.components.device_sun_light_trigger: debug
#    homeassistant.components.script: info
#    homeassistant.components.rfxtrx: info
#    custom_components.xiaomi: debug
#    homeassistant.components.sensor.command_line: debug
#    homeassistant.components.shell_command: debug
#    miflora.miflora_poller: debug
#    homeassistant.components.sensor.miflora: debug
#    homeassistant.core: info

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: mosquitto
  password: mosquitto
  protocol: 3.1 
  discovery: true
  discovery_prefix: home

device_tracker:
#  - platform: icloud
#    username: marcus.ronelius@gmail.com
#    password: N1ntendo1
#    account_name: Marcus
#    icloud_set_interval: 30

#  - platform: icloud
#    username: schmidt.7@outlook.com
#    password: Tegelsten88
#    account_name: Katarina
#    icloud_set_interval: 30
  - platform: asuswrt
    host: 192.168.1.1
    username: admin
    password: !secret asuswrt_password

zone:
  name: Work
  latitude: !secret zone_work_latitude
  longitude: !secret zone_work_longitude
  radius: 250
  icon: mdi:worker
  #track_ios: true

switch:

xiaomi:

light:
  - platform: hue
    host: 192.168.1.8

ios:

notify:

volvooncall:
  username: marcus.ronelius@gmail.com
  password: !secret volvooncall_password
  name:
    ete881: 'ETE881'

group: !include groups.yaml
scene: !include_dir_list scenes
automation: !include_dir_merge_list automation
script: !include scripts/radio.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml

shell_command:
  radio: '/home/pi/.homeassistant/scripts/radio.sh {{ mediaplayer }} {{ station }}'
  backup_hass: '/home/pi/.homeassistant/scripts/backup_hass.sh'

