- platform: miflora
  name: miflower_kitchenflower
  mac: 'C4:7C:8D:61:FD:A7'
  monitored_conditions:
    - moisture
    - temperature
    - light
    - conductivity
    - battery


- platform: speedtest
  minute:
    - 0
    - 5
    - 10
    - 15
    - 20
    - 25
    - 30
    - 35
    - 40
    - 45
    - 50
  monitored_conditions:
    - download
    - upload