automation:
#######################
#
# Backup of HASS Configuration files
#
#######################
  - alias: "backup home assistant configuration files"
    trigger:
      platform: time
      at: '05:00:00'
    action:
      service: shell_command.backup_hass