automation:
#  - alias: Alarm on when bedroom covers goes down
#    trigger:
#      - platform: state
#        entity_id: cover.qubino_zmnhod1_flush_shutter_dc_level
#        from: 'open'
#        to: 'closed'
#    condition:
#      condition: and
#      conditions:
#        - condition: time
#          after: '20:00'
#    action:
#      - service: alarm_control_panel.alarm_arm_home
#        entity_id: alarm_control_panel.solbacken_44_alarm
#        data:
#          code: !secret alarm_code

  - alias: KNX scene All Off also include other indoor lights
    trigger:
      - platform: state
        entity_id: switch.alllightsoff
    action:
      - service: scene.turn_on
        entity_id: scene.indoor_off
############################
#
# Automatic Bedtime if no movement for
# 10 minutes and time is after 22:00
#
############################
#  - alias: Automatic bedtime
#    trigger:
#      - platform: state
#        entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
#        to: 'off'
#        for:
#          minutes: 10
#    condition:
#      condition: and
#      conditions:
#        - condition: time
#          after: '22:00'
#        - condition: state
#          entity_id: media_player.apple_tv_vardagsrum
#          state: 'paused'
#        - condition: state
#          entity_id: media_player.spotify
#          state: 'paused'
#        - condition: state
#          entity_id: light.vardagsrum
#          state: 'on'
#    action:
#          service: script.bedtime
#
############################
#
# Send actionable notification asking
# if bedtime
#
############################
#  - alias: Actionable bedtime notification
#    trigger:
#      platform: time
#      at: '22:30'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: input_boolean.someone_home
#          state: 'on'
#        - condition: state
#          entity_id: light.vardagsrum
#          state: 'on'
#    action:
#      service: notify.notify
#      data:
#        title: "Läggdags"
#        message: "Snart dags för sängen"
#        data:
#          push:
#            badge: 0
#            category: "BEDTIME" # Needs to match the top level identifier you used in the ios configuration
#
#  - alias: Bedtime action goodnight tapped
#    trigger:
#      platform: event
#      event_type: ios.notification_action_fired
#      event_data:
#        actionName: BEDTIME_TRIGGER
#    action:
#      service: script.bedtime
#
#  - alias: Bedtime action snooze 15 tapped
#    trigger:
#      platform: event
#      event_type: ios.notification_action_fired
#      event_data:
#        actionName: BEDTIME_SNOOZE15
#    action:
#      service: script.bedtime_snooze15
#
#  - alias: Bedtime action snooze 30 tapped
#    trigger:
#      platform: event
#      event_type: ios.notification_action_fired
#      event_data:
#        actionName: BEDTIME_SNOOZE30
#    action:
#      service: script.bedtime_snooze30
#


script:
  bedtime:
    sequence:
      - service: scene.turn_on
        entity_id: scene.livingroom_off
  bedtime_snooze15:
    sequence:
      - service: notify.notify
        data:
          title: "Läggdags"
          message: "Snoozar i 15 minuter"
      - delay:
          minutes: 15
      - service: automation.trigger
        entity_id: automation.actionable_bedtime_notification
  bedtime_snooze30:
    sequence:
      - service: notify.notify
        data:
          title: "Läggdags"
          message: "Snoozar i 30 minuter"
      - delay:
          minutes: 30
      - service: automation.trigger
        entity_id: automation.actionable_bedtime_notification



ios:
  push:
    categories:
      - name: Bedtime
        identifier: 'BEDTIME'
        actions:
          - identifier: 'BEDTIME_TRIGGER'
            title: 'Godnatt'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'BEDTIME_SNOOZE15'
            title: 'Snooze 15min'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'BEDTIME_SNOOZE30'
            title: 'Snooze 30min'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
