automation:
  - alias: Coming home
  # Will trigger if any of the below are 'home'
    trigger:
      - platform: state
        entity_id: group.family_devices
        from: 'not_home'
        to: 'home'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '06:30'
          before: '22:30'

    action:
      - service: script.family_home_alarm_off
      # Greeting
      #- service: script.family_home_tts_greeting
      # Music
      #- service: script.family_home_music
      # Lights
      #- service: script.family_home_adjust_lights




script:
  family_home_alarm_off:
    sequence:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.solbacken_44_alarm
        data:
          code: !secret alarm_code
  family_home_tts_greeting:
    sequence:
      - service: script.turn_on
        entity_id: script.speech_processing
        data_template:
          variables:
            speech_message: >
              {{ [
                "Välkommen hem.",
                "Äntligen är ni hemma, Molle har väntat så.",
                "Välkommen hem. Vi har saknat dig, eller i alla fall Molle.",
                "Äntligen hemma.",
                "Hallå där, välkommen hem.",
                "Skönt att ha er hemma igen."
              ] | random }}

  family_home_music:
    sequence:
      # - service: input_select.select_option
      #   data:
      #     entity_id: input_select.playlist
      #     option: 'Feeling good låtar!'
      # - service: input_select.select_option
      #   data:
      #     entity_id: input_select.speaker
      #     option: 'Kök'
      - service: script.turn_on
        entity_id: script.speech_processing
        data_template:
          variables:
            speech_message: >
              {{ [
                "Jag sätter igång lite musik att njuta till.",
                "Jag sätter igång lite musik",
                "Här kommer lite musik",
                "Jag börjar spela lite musik nu",
                "Jag tänkte att vi kunde sätta igång lite musik"
              ] | random }}
      - service: media_player.select_source
        data:
          entity_id: media_player.kitchen
          source: 'Feeling good låtar!'
      - service: media_player.shuffle_set
        data:
          entity_id: media_player.kitchen
          shuffle: true
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: 0.2
      - service: media_player.media_play
        data:
          entity_id: media_player.kitchen

  family_home_adjust_lights:
    sequence:
        # This is a Condition, everything after this sequence
        # will only be triggered if condition is true
      - condition: sun
        after: sunset
        after_offset: "-1:00:00"

      - service: scene.turn_on
        entity_id: scene.livingroom_normal
      - service: scene.turn_on
        entity_id: scene.bedroom_normal
