automation:
  - alias: Coming home
  # Will trigger if any of the below are 'home'
    trigger:
      - platform: state
        entity_id: device_tracker.marcus_iphone
        to: 'home'
      - platform: state
        entity_id: device_tracker.katarinas_iphone
        to: 'home'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '06:30'
          before: '23:30'
        - condition: state
          entity_id: input_boolean.someone_home    
          state: 'off'
    action:
        service: script.family_home


script:
  family_home:
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.someone_home

        # This is a Condition, everything after this sequence 
        # will only be triggered if condition is true
      - condition: sun
        after: sunset
        after_offset: "-1:00:00"

      - service: scene.turn_on
        entity_id: scene.livingroom_low
      - service: scene.turn_on
        entity_id: scene.bedroom_normal


input_boolean:
  someone_home:
    initial: on