#######################
#
# Good morning automation
#
#######################

automation:
  - alias: Alarm off when going downstairs in the morning
    trigger:
        platform: state
        entity_id: group.downstairs_sensors
        to: 'on'
    condition:
      - condition: and
        conditions:
        # Can trigger?
        - condition: time
          after: '06:00:00'
          before: '13:00:00'
        - condition: state
          entity_id: group.family_devices
          state: 'home'
    action:
        - service: alarm_control_panel.alarm_disarm
          entity_id: alarm_control_panel.solbacken_44_alarm
          data:
            code: !secret alarm_code

  - alias: Enable Can trigger good morning
    trigger:
        platform: time
        at: '6:00'
    action:
        service: homeassistant.turn_on
        entity_id: input_boolean.can_trigger_good_morning

  - alias: Disable Can trigger good morning
    trigger:
        platform: sun
        event: sunrise
        offset: "04:00:00"
    action:
        service: homeassistant.turn_off
        entity_id: input_boolean.can_trigger_good_morning

  # This is the automation which serves to allow the designated sensors
  # to trigger the good morning input boolean
  - alias: Good morning
    trigger:
      - platform: state
        entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
        to: 'on'
      # ++++++
      # Keep adding sensors that can trigger good morning
      # ++++++

    condition:
      - condition: and
        conditions:
        # Can trigger?
        - condition: state
          entity_id: input_boolean.can_trigger_good_morning
          state: 'on'
        # Luminance
        - condition: numeric_state
          entity_id: sensor.aeotec_zw100_multisensor_6_luminance
          below: 2
        # Lights
        - condition: state
          entity_id: group.livingroom_lights
          state: 'off'

    action:
        service: script.good_morning



script:
  good_morning:
    sequence:
      - service: homeassistant.turn_off
        entity_id: input_boolean.can_trigger_good_morning

      - service: scene.turn_on
        entity_id: scene.livingroom_low

      - service: script.turn_on
        entity_id: script.speech_engine
        data_template:
          variables:
            goodmorninggreeting: >
              {{ [
                "God morgon. Hoppas du har sovit gott. ",
                "God morgon. ",
                "Hallå där, hoppas du sovit gott. ",
                "God morgon. Ny dag, nya möjligheter. ",
                "God morgon. Idag kommer bli en bra dag. "
              ] | random }}

              {% if states('sensor.weather_cloudiness')|int <= 20 %}
                {{ [
                  "Det ser ut att bli en fin dag med lite moln. Temperaturen kommer ungefär att vara " ~ states.sensor.weather_temperature.state | int + " grader.",
                  "Idag blir det en fin dag med inte så mycket moln. Vi kommer få en temperatur på ungefär " ~ states.sensor.weather_temperature.state | int + " grader.",
                  "Idag kommer solen att skina. Temperaturen hamnar ungefär på " ~ states.sensor.weather_temperature.state | int + " grader."
                ] | random }}
              {% endif %}

              {% if states('sensor.weather_cloudiness')|int > 20 and states('sensor.weather_cloudiness')|int <= 50 %}
                {{ [
                  "Idag blir det halvklart väder. Temperaturen ligger ungefär runt " ~ states.sensor.weather_temperature.state | int + " grader.",
                  "Det kommer att vara halvklart väder med en del moln. Vi kommer få en temperatur på ungefär " ~ states.sensor.weather_temperature.state | int + " grader.",
                  "Vädret idag kommer bara halvklart till molnigt. Temperaturen hamnar ungefär på " ~ states.sensor.weather_temperature.state | int + " grader."
                ] | random }}
              {% endif %}

              {% if states('sensor.weather_cloudiness')|int > 50 %}
                {{ [
                  "Vi har en del moln idag. Temperaturen kommer ungefär att vara " ~ states.sensor.weather_temperature.state | int + " grader.",
                  "Idag blir det mulet. Vi kommer få en temperatur på ungefär " ~ states.sensor.weather_temperature.state | int + " grader.",
                  "Vi kommer få en hel del moln idag. Temperaturen kommer ungefär att ligga på " ~ states.sensor.weather_temperature.state | int + " grader.",
                  "Vädret idag kommer bli ordentligt molnigt. Temperaturen är ungefär " ~ states.sensor.weather_temperature.state | int + " grader.",
                  "Molnen ligger tätt idag. Temperaturen hamnar ungefär på " ~ states.sensor.weather_temperature.state | int + " grader."
                ] | random }}
              {% endif %}

              {% if now().weekday() in (0,1,2,3,4) %}
                {{ [
                  "Det kommer ungefär att ta " ~ states.sensor.home_to_work + " att åka till jobbet.",
                  "Med nuvarande trafikläge så kommer det ungefär att ta " ~ states.sensor.home_to_work.attributes.duration_in_traffic + " att åka till jobbet.",
                  "När du åker till jobbet så kommer det ungefär att ta " ~ states.sensor.home_to_work.attributes.duration_in_traffic + "."
                ] | random }}
              {% endif %}


input_boolean:
  can_trigger_good_morning:
    initial: off
