automation:
  - alias: Leaving home
  # Will only trigger if all are 'not_home'
    trigger:
      - platform: state
        entity_id: group.family_devices
        from: 'home'
        to: 'not_home'
    action:
          service: script.family_away


script:
  family_away:
    sequence:

      - service: script.turn_on
        entity_id: script.family_away_lights_off

      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.solbacken_44_alarm
        data: 
          code: !secret alarm_code
      # - delay:
      #   minutes: 5
        # This is a Condition, everything after this sequence
        # will only be triggered if condition is true
      # - condition: state
      #   entity_id: binary_sensor.door_window_sensor_158d00018379dd # Badrumsdörr
      #   state: 'off'
        # If Badrumsdörr is closed (which is state off)
        # send a notification because Molle needs to be able
        # to do his popo in the bathroom when family is not home
      # - service: notify.notify
      #   data:
      #     title: 'Solbacken 44'
      #     message: 'Badrumsdörren är stängd, åk hem igen och öppna den åt Molle'


  family_away_lights_off:
    sequence:
      - service: logbook.log
        data_template:
          name: Family away delay
          message: Waiting 5 minutes to turn off lights (only if someone still not home)
      - delay:
          minutes: 5
      - condition: state
        entity_id: group.family_devices
        state: 'not_home'
      - service: light.turn_off
        entity_id: group.all_indoor_lights
