automation:
  - alias: All lights downstairs off when stairwell switch changes state
  # Will trigger if any of the below are 'home'
    trigger:
      - platform: state
        entity_id: switch.downstairslightsoff
    action:
      - service: scene.turn_on
        entity_id: scene.downstairs_off
      - service: media_player.media_pause
        data:
          entity_id: media_player.kitchen
