automation:
#######################
#
# Normal light when mediaplayer paused/stopped
# Rooms: Livingroom
#
#######################
  - alias: 'Mediaplayer (livingroom) paused/stopped'
    trigger:
      - platform: state
        entity_id: media_player.apple_tv_vardagsrum
        from: 'playing'
        to: 'paused'
    condition:
      - condition: sun
        after: sunset
        after_offset: "-1:30:00"
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_normal



#######################
#
# Low light when mediaplayer playing
# Rooms: Livingroom
#
#######################
  - alias: "Mediaplayer (livingroom) playing"
    trigger:
      - platform: state
        entity_id: media_player.apple_tv_vardagsrum
        to: 'playing'
        from: 'paused'
    condition:
      - condition: sun
        after: sunset
        after_offset: "-1:30:00"
    action:
        service: scene.turn_on
        entity_id: scene.livingroom_movie