- alias: 'Bedtime'
  trigger:
    - platform: state
      entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
      to: 'off'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: time
        after: '22:00'
      - condition: state
        entity_id: media_player.apple_tv_vardagsrum
        state: 'paused'
      - condition: state
        entity_id: media_player.spotify
        state: 'paused'
  action:
        service: script.bedtime