#######################
#
# Good morning automation
#
#######################

# --------------
# Prerequisites. Make sure we dont trigger main scene more than once
# --------------
- alias: Enable Can trigger good morning
  trigger:
      platform: time
      at: '5:00'
  action: 
      service: homeassistant.turn_on
      entity_id: input_boolean.can_trigger_good_morning

- alias: Disable Can trigger good morning
  trigger:
      platform: sun
      event: sunrise
      offset: "04:00:00"
  action: 
      service: homeassistant.turn_off
      entity_id: input_boolean.can_trigger_good_morning

# This is the automation which serves to allow the designated sensors
# to trigger the good morning input boolean
- alias: Good morning
  trigger:
    - platform: state
      entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor
      to: 'on'
    # ++++++
    # Keep adding sensors that can trigger good morning
    # ++++++

  condition:
    - condition: and
      conditions:
      # Can trigger?
      - condition: state
        entity_id: input_boolean.can_trigger_good_morning
        state: 'on'
      # Luminance
      - condition: numeric_state
        entity_id: sensor.aeotec_zw100_multisensor_6_luminance
        below: 2
      # Lights
      - condition: state
        entity_id: group.livingroom_lights
        state: 'off'
      # ++++++
      # Keep adding sensors that can trigger good morning
      # ++++++

  action: 
      service: script.good_morning