#turns it on at 5am
- alias: Enable First Morning Trigger
  trigger:
    - platform: time
      at: '5:00'
  action: 
    service: homeassistant.turn_on
    entity_id: input_boolean.trigger_first_morning

# turns it off after sunrise only if it hasnt already turned off. 
# Its being turned off in light automation "First Morning Motion Livingroom"
- alias: Disable First Morning Trigger
  trigger:
    - platform: sun
      event: sunrise
      offset: "04:00:00"
  condition:
    condition: state
    entity_id: input_boolean.trigger_first_morning
    state: 'on'
  action: 
    service: homeassistant.turn_off
    entity_id: input_boolean.trigger_first_morning



- alias: Family away
# Will only trigger if all are 'not_home'
  trigger:
      platform: template
      value_template: "{% if (is_state('device_tracker.marcus_iphone','not_home')) and (is_state('device_tracker.katarinas_iphone','not_home')) %}true{% endif %}"
  condition:
    condition: and
    conditions:
      - condition: time
        after: '06:30'
        before: '23:30'
      - condition: state
        entity_id: input_boolean.someone_home    
        state: 'on'
  action:
      service: homeassistant.turn_off
      entity_id: input_boolean.someone_home

- alias: Family home
# Will trigger if any of the below are 'home'
  trigger:
    - platform: state
      entity_id: device_tracker.marcus_iphone
      to: 'home'
    - platform: state
      entity_id: device_tracker.katarinas_iphone
      to: 'home'
  condition:
    condition: state
    entity_id: input_boolean.someone_home
    state: 'off'
  action:
      service: homeassistant.turn_on
      entity_id: input_boolean.someone_home