#######################
#
# Katarinas phone low battery
#
#######################
- alias: 'Katarina battery notification'
  trigger:
    - platform: numeric_state
      entity_id: sensor.katarinas_iphone_battery_level
      below: 6
  action:
    - service: notify.ios_marcus_iphone
      data:
        message: 'Katarina har mindre än 5% batteri kvar'

#######################
#
# Marcus low battery
#
#######################
- alias: 'Marcus battery notification'
  trigger:
    - platform: numeric_state
      entity_id: sensor.marcus_iphone_battery_level
      below: 6
  action:
    - service: notify.ios_katarinas_iphone
      data:
        message: 'Marcus har mindre än 5% batteri kvar'

#######################
#
# Multisensor low battery
# Livingroom
#
#######################
- alias: 'Multisensor livingroom battery notification'
  trigger:
    - platform: numeric_state
      entity_id: zwave.aeotec_zw100_multisensor_6
      value_template: '{{ state.attributes.battery_level }}'
      below: 11
  action:
    - service: notify.ios_marcus_iphone
      data:
        title: 'Ulfsparregatan 11D'
        message: 'Multisensorn i vardagsrummet har låg batterinivå. Nuvarande nivå 10%'

#######################
#
# Volvo Heater started
#
#######################
- alias: "VoC Heater notification start"
  trigger:
    - platform: state
      entity_id: switch.ete881_heater
      to: 'on'
  action:
    - service: notify.ios_marcus_iphone
      data:
        title: Volvo on Call
        message: 'Värmare för ETE881 har startats'

#######################
#
# Volvo Heater stopped
#
#######################
- alias: "VoC Heater notification stop"
  trigger:
    - platform: state
      entity_id: switch.ete881_heater
      to: 'off'
  action:
    - service: notify.ios_marcus_iphone
      data:
        title: Volvo on Call
        message: 'Värmare för ETE881 har stoppats'

#######################
#
# Christmasstar low moisture
# Flower sensor
#
#######################
- alias: 'Christmasstar moisture notification'
  trigger:
    - platform: numeric_state
      entity_id: sensor.miflower_kitchenflower_moisture
      below: 21
  action:
    - service: notify.ios_marcus_iphone
      data:
        title: 'Ulfsparregatan 11D'
        message: 'Julstjärnan i köket behöver vattnas, just nu {{ states.sensor.miflower_kitchenflower_moisture.state }}% fuktighet'
    - service: notify.ios_katarinas_iphone
      data:
        title: 'Ulfsparregatan 11D'
        message: 'Julstjärnan i köket behöver vattnas, just nu {{ states.sensor.miflower_kitchenflower_moisture.state }}% fuktighet'

#######################
#
# Christmasstar low battery
# Flower sensor
#
#######################
- alias: 'Christmasstar battery notification'
  trigger:
    - platform: numeric_state
      entity_id: sensor.miflower_kitchenflower_battery
      below: 11
  action:
    - service: notify.ios_marcus_iphone
      data:
        title: 'Ulfsparregatan 11D'
        message: 'Julstjärnans sensor har låg batterinivå. Nuvarande nivå {{ states.sensor.miflower_kitchenflower_battery.state }}%'




