automation:
  - alias: 'Guestroom window stand light on based on KNX switch trigger'
    trigger:
      - platform: state
        entity_id: light.childrensroomwindow
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.barnrum

  - alias: 'Guestroom window stand light off based on KNX switch trigger'
    trigger:
      - platform: state
        entity_id: light.childrensroomwindow
        to: 'off'
    action:
      service: light.turn_off
      entity_id: light.barnrum
