volvooncall:
  username: marcus.ronelius@gmail.com
  password: !secret volvooncall_password
  name:
    ete881: 'ETE881'

camera:
  name: car_location
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.volvo_ete881.attributes.latitude }},{{ states.device_tracker.volvo_ete881.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.volvo_ete881.attributes.latitude }},{{ states.device_tracker.volvo_ete881.attributes.longitude }}
  limit_refetch_to_url_change: true

sensor:
  - platform: car_milage_per_month
    odometer_sensor: sensor.ete881_odometer
    scan_interval: 3600
    unit_of_measurement: 'km'

  - platform: template
    sensors:
      ete881_odometer_template:
        unit_of_measurement: 'mil'
        value_template: '{{ states.sensor.ete881_odometer.state | multiply(1) / 10 }}'
      ete881_range_template:
        unit_of_measurement: 'mil'
        value_template: '{{ states.sensor.ete881_range.state | multiply(1) / 10 }}'

  - platform: template
    sensors:
      car_locked:
        value_template: '{% if is_state("sensor.car_locked_state", False) %} Öppet {% else %} Låst {% endif %}'
        friendly_name: Dörrar & lås

  - platform: mqtt
    name: "car_regnr"
    state_topic: "/home/car"
    value_template: '{{ value_json.regnr }}'

  - platform: mqtt
    name: "car_model"
    state_topic: "/home/car"
    value_template: '{{ value_json.model }}'

  - platform: mqtt
    name: "car_locked_state"
    state_topic: "/home/car"
    value_template: '{{ value_json.locked }}'

  - platform: mqtt
    name: car_location_latitude
    state_topic: "/home/car"
    value_template: '{{ value_json.location_latitude}}'

  - platform: mqtt
    name: car_location_longitude
    state_topic: "/home/car"
    value_template: '{{ value_json.location_longitude}}'