sensor:
  - platform: yr
    name: "weather"
    friendly_name: "Väder"
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness

  - platform: command_line
    name: weather wind direction cmd
    command: 'sh /home/pi/.homeassistant/scripts/wind_direction.sh {{ states.sensor.weather_wind_direction.state }}'
    unit_of_measurement: "Riktning"